config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  resources :employees do
    member do
      post :goodjob
    end
  end

  root to: "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
    validates :name, presence: true
    has_many :vote_logs
end

app/models/cat.rb
class Cat < ApplicationRecord
  validates :name, presence: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true
  validates :tel, presence: true
  validates :email, presence: true
  has_many :good_job_logs, dependent: :destroy
  # 如果與他相關聯的資料庫被刪掉了，就會跟著刪掉
end

app/models/good_job_log.rb
class GoodJobLog < ApplicationRecord
  belongs_to :employee, counter_cache: true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate, counter_cache: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create 
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_path, notice: 'Books Created !'
    else
      render :new
    end
  end

  def show
    @book = Book.find_by!(id: params[:id])
  end

  def edit 
    @book = Book.find_by!(id: params[:id])
  end

  def update
    @book = Book.find_by!(id: params[:id])

    if @book.update(book_params)
      redirect_to books_path, notice: 'Books Updated !'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find_by!(id: params[:id])
    @book.destroy
    redirect_to books_path, notice: 'Books Deleted !'
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :info)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :find_cat, except: [:index, :new, :create]

  def index
    @cats = Cat.all
  end    

  def new
    @cat = Cat.new
  end
  
  def create
    @cat =  Cat.new(cat_params)

    if @cat.save
      redirect_to cats_path, notice: 'Cat Created !'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update

    if @cat.update(cat_params)
      redirect_to cats_path, notice: 'Cat Updated !'
    else
      render :edit
    end
  end

  def destroy
    @cat.destroy
    redirect_to cats_path, notice: 'Cat Deleted !'
  end

  private
  
  def cat_params
    params.require(:cat).permit(:name, :age, :breed)
  end

  def find_cat
    @cat = Cat.find_by!(id: params[:id])
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :find_employee, except: [:index, :new, :create]

  def index
    @employees = Employee.all
    @employee_created_time = Employee.group_by_week(:created_at).count
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employees_path, notice: 'Employee Created !'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update

    if @employee.update(employee_params)
      redirect_to employees_path, notice: 'Employee Updated !'
    else
      render :edit
    end
  end

  def destroy
    @employee.destroy
    redirect_to employees_path, notice: 'Employee Deleted !'
  end

  def goodjob
    @employee.good_job_logs.create(ip_address: request.remote_ip)
    redirect_to employees_path, notice: 'Nice !'
  end

  private
  def employee_params
    params.require(:employee).permit(:name, :age, :tel, :email, :intro)
  end
  def find_employee
    @employee = Employee.find_by!(id: params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/devises_helper.rb
module DevisesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/employees/_employee.html.erb
<tr>
      <td><%= link_to 'Nice', goodjob_employee_path(employee.id), method: 'post' %></td>
      <td><%= employee.good_job_logs.size %></td>
      <td><%= link_to employee.name, employee_path(employee.id) %></td>
      <td><%= employee.age %></td>
      <td><%= employee.tel %></td>
      <td><%= employee.email %></td>
      <td><%= employee.intro %></td>
      <td><%= link_to 'Update Info', edit_employee_path(employee.id) %></td>
      <td><%= link_to 'Fire Employee', employee_path(employee.id), method: 'delete', data: {confirm:'Are you sure!?'} %></td>
  </tr>

app/views/employees/_form.html.erb
<% if employee.errors.any? %>
  <% employee.errors.full_messages.each do |message| %>
    <%= message %>
    <br>
  <% end %>
<% end %>



<section class="new">
  <%= form_for(employee) do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :age %>
      <%= form.number_field :age %>
    </div>

    <div>
      <%= form.label :tel %>
      <%= form.number_field :tel %>
    </div>

     <div>
       <%= form.label :email %>
       <%= form.email_field :email %>
     </div>

     <div>
       <%= form.label :intro %>
       <%= form.text_area :intro %>
     </div>

     <div aria-label="aaa"><%= form.submit 'send profile' %></div>
  <% end %>

  
</section>

app/views/employees/edit.html.erb
<h1>Update Employee</h1>

<%= render 'form', employee: @employee %>

app/views/employees/index.html.erb
<h1>All Employees</h1>

<%= link_to 'Add Employee' , new_employee_path %>

<table class="font-bold ">
  <tr>
    <td></td>
    <td>Goodjob</td>
    <td>Name</td>
    <td>Age</td>
    <td>Tel</td>
    <td>Email</td>
    <td>Intro</td>
    <td>Action 1</td>
    <td>Action 2</td>
  </tr>



  <%= render partial: "employee", collection: @employees %>

  <!-- <%# <% @employees.each do |employee| %> 
    <%# <%= render 'employee', employee: employee %> 
  <%# <% end %>  -->
  <%= line_chart @employee_created_time, xtitle: "時間時間", ytitle: "Population",  curve: false,  legend: "top", dataset: {borderWidth: 5}, color: ["#f00", "#00f"], adapter: "highcharts" %>

  <%= pie_chart Employee.group(:age).count, donut: true, thousands: ",", dataset: {borderWidth: 3}, empty: "No data", title: "Awesome chart", adapter: "highcharts" %>

  <%= column_chart Employee.group(:age).count, prefix: "$", dataset: {borderWidth: 0}, stacked: true, thousands: ",", round: 2, zeros: true, adapter: "highcharts" %>

  <%= bar_chart Employee.group(:name).sum(:good_job_logs_count), empty: "No data", adapter: "highcharts" %>


</table>

app/views/employees/new.html.erb
<h1>Add Employee</h1>

<%= render 'form', employee: @employee %>

app/views/employees/show.html.erb
<h1><%= @employee.name %></h1>

<ul>
  <li><%= @employee.age %></li>
  <li><%= @employee.tel %></li>
  <li><%= @employee.email %></li>
  <li><%= @employee.intro %></li>
</ul>

<button><%= link_to 'All Employees', employees_path %></button>